server:
  rootPath: /*
  gzip:
    enabled: true
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 9000
  adminConnectors: []

logging:
  level: INFO
  loggers:
    com.moo.ecommerce: DEBUG

service:
  stubbed: yes
  stubData:
    paymentUrl: "https://testpage.payments.digitalriver.com/pay/?creq=BEii9whIovYlP0DgYuO9fvhp-x6z9R9CinJhI9A93R1Hz2ZDfjbEFpj2kJD960uSo55-jt96d00ehMkPuTK2A_8C7bPqILBjrEnXUZe0PAtTaOK3UBRvintnu8wwMD80FyMLvnmCIQE1zHn-LZGgDKUVbtyI6VsuqNneAaD6KHo_wXIBh47v2Xk6biOiz35HoeSWZM8QGsZPNM-EEaxtpYpkowJJSuYWgbrIvcNi2aAWGGnVNcYswCJL5RokAXffYHNNCeuS1UGipKrH7i6lx0aQlUZNvxV5gskDh_jICyTjKL37UKPwMjKXCSDydKoCS7A1-LYa0XxWrQAEtfVjA9dFqbYJ-_HbEuYySH91J10JN-sEmfgBzCUmFNbiZtl9a9QREpVj1pc9I_AC7OStkjDDaK6a_xtEFKXiYugG_U-N15sYtrnaHcy41CIyyAbBxHSCtAvyxFRJXHG4pgchQZ8PCPBwElL3DsIQPCFiRJltzbvbE73iaDH7rV9FPOegcshESY39Q_uWf35xPO5NuI1huQwwvRNmv_-Scx9juNpQMhOngsoGAeobCQfJLH6ugU0RcoPjN5ocSl6ET_P-Mtaw3Tma5BM40Px1uEplvEYQT7Xr37qza0XlWxtz8B6vtEy6yIsimeWKUdzScCJM2xm359hq4nRNrrQhL18qe9RFsT6dLT3xH3EJ_3vy9UntjuHwihAwu5px"
