server:
  rootPath: /*
  gzip:
    enabled: true
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 9000
  adminConnectors: []

logging:
  level: INFO
  loggers:
    com.moo.ecommerce: DEBUG

service:
  stubbed: yes
  stubData:
